importScripts('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js');
self.onmessage=async e=>{try{if(e.data?.type!=='parse')return;const wb=XLSX.read(e.data.buffer,{type:'array',cellDates:true,cellNF:false,cellStyles:false});const sheets=wb.SheetNames||[];const post=(message,percent)=>self.postMessage({type:'progress',message,percent});post('Lectura de hojas completada',20);
const sheetPart=p=>sheets.find(s=>s.toUpperCase().includes(p.toUpperCase()))||null;const rowsOf=name=>name&&wb.Sheets[name]?XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null,raw:true}):[];const rowsPart=p=>rowsOf(sheetPart(p));
const norm=v=>String(v??'').toUpperCase().replace(/[.\-\s]/g,'');const n=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;const x=String(v??'').replace(/\$/g,'').replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.');const z=parseFloat(x);return Number.isFinite(z)?z:0};
const headerRow=(rows,req)=>{const r=req.map(x=>x.toUpperCase());let best=-1,score=0;for(let i=0;i<Math.min(rows.length,30);i++){const t=(rows[i]||[]).map(v=>String(v??'').toUpperCase()).join(' | ');const sc=r.filter(x=>t.includes(x)).length;if(sc>score){score=sc;best=i}}return best};
const objects=(rows,req,max=30000)=>{const h=headerRow(rows,req);if(h<0)return[];const header=rows[h].map(v=>String(v??'').trim());const out=[];for(let i=h+1;i<Math.min(rows.length,max);i++){const r=rows[i];if(!r||r.every(v=>v==null||v===''))continue;const o={};header.forEach((k,j)=>{if(k)o[k]=r[j]});out.push(o)}return out};
const get=(o,keys)=>{for(const k of keys){const hit=Object.keys(o).find(x=>x.toUpperCase().replace(/\s+/g,' ').includes(k.toUpperCase()));if(hit&&o[hit]!=null&&o[hit]!=='')return o[hit]}return ''};
post('Procesando INE',30);const ir=rowsPart('INE');const ine={totalNeto:0,totalKg:0,totalPromedio:0,netoHarinas:0,kgHarinas:0,promedioHarinas:0,items:[],periodo:''};const rh=ir.findIndex(r=>String(r?.[0]||'').toUpperCase().includes('ETIQUETAS DE FILA'));if(rh>=0){ine.periodo=String(ir[2]?.[1]||'')+' '+String(ir[3]?.[1]||'');for(let i=rh+1;i<ir.length;i++){const name=String(ir[i]?.[0]??'').trim();if(!name)continue;const net=n(ir[i]?.[1]),kg=n(ir[i]?.[2]),avg=n(ir[i]?.[3]);if(/TOTAL GENERAL/i.test(name)){ine.totalNeto=net;ine.totalKg=kg;ine.totalPromedio=avg;continue}if(net||kg)ine.items.push({name,neto:net,kg,promedio:avg,vn:n(ir[i]?.[4]),kgp:n(ir[i]?.[5])})}}for(const r of ir){const label=String(r?.[0]??'').toUpperCase();if(label==='NETO HARINAS')ine.netoHarinas=n(r?.[1]);if(label.includes('KG HARINAS'))ine.kgHarinas=n(r?.[1]);if(label.includes('VALOR PROMEDIO HARINAS'))ine.promedioHarinas=n(r?.[1])}
post('Procesando Sacos y Granel',42);const sr=rowsPart('NESTLE SACOS');let ventasSacos=0,kgSacos=0;const sacItems=[];for(const r of sr){if(String(r?.[1]||'')||String(r?.[2]||'')){const v=n(r?.[3]);if(v)sacItems.push({clave:String(r?.[1]||''),clasificacion:String(r?.[2]||''),ventas:v})}}const totalRow=sr.find(r=>String(r?.[1]||'').toUpperCase()==='TOTAL GENERAL');ventasSacos=totalRow?n(totalRow[3]):sacItems.filter(x=>x.clave!=='N.A').reduce((s,x)=>s+x.ventas,0);const kgRow=sr.find(r=>String(r?.[6]||'').toUpperCase().includes('TOTAL SACOS KG'));kgSacos=kgRow?n(kgRow[7]):0;
let granelItems=[];const primary=rowsPart('NESTLE Y CPW');for(const r of primary){const prod=String(r?.[6]||'').trim();if(prod&&/GRANEL/i.test(prod)&&!/TOTAL/i.test(prod)){const nums=(r.slice(7)).map(n);const kg=nums.reduce((a,b)=>a+b,0);if(kg)granelItems.push({fuente:sheetPart('NESTLE Y CPW'),producto:prod,kg})}}let totalGranel=0;const tg=primary.find(r=>String(r?.[6]||'').toUpperCase().includes('TOTAL GRANEL'));if(tg)totalGranel=n(tg[7]);else totalGranel=granelItems.reduce((s,x)=>s+x.kg,0);
post('Construyendo documentos y clientes',60);const documents=[];for(const [part,req] of [['LIBRO',['NRO. DOCTO','FECHA']],['GUIAS',['FOLIO','FECHA']],['BASE DE DATOS',['FOLIO','ORIGEN/DESTINO']]]){const name=sheetPart(part);if(!name)continue;for(const o of objects(rowsOf(name),req,30000)){documents.push({fuente:name,fecha:get(o,['FECHA']),folio:get(o,['NRO. DOCTO','FOLIO','NRO']),tipo:get(o,['TIPO DOC','TIPO','DOCTO','TRANSACCIÓN']),cliente:get(o,['NOMBRE CLIENTE','NOMBRE RECEPTOR','ORIGEN/DESTINO','CLIENTE']),rut:get(o,['R.U.T. CLIENTE','RUT RECEPTOR','RUT']),neto:get(o,['NETO AFECTO','NETO']),iva:get(o,['I.V.A.','IVA']),total:get(o,['VALOR TOTAL','TOTAL','VALOR MOVTO'])})}}
const clientsMap=new Map();const addClient=(rut,nombre,doc)=>{const key=norm(rut||nombre);if(!key)return;if(!clientsMap.has(key))clientsMap.set(key,{key,rut:String(rut||''),nombre:String(nombre||'').trim()||'(Sin nombre)',documentos:[],neto:0,iva:0,total:0});const c=clientsMap.get(key);if(nombre&&(!c.nombre||c.nombre==='(Sin nombre)'))c.nombre=String(nombre).trim();if(doc){c.documentos.push(doc);c.neto+=n(doc.neto);c.iva+=n(doc.iva);c.total+=n(doc.total)}};
for(const d of documents){if(d.rut||d.cliente)addClient(d.rut,d.cliente,d)}
post('Construyendo guías, NC/ND e IVA',78);const guides=[];const gn=sheetPart('GUIAS');if(gn)for(const o of objects(rowsOf(gn),['FOLIO','RUT RECEPTOR','TOTAL'],20000))guides.push({folio:get(o,['FOLIO']),fecha:get(o,['FECHA']),estado:get(o,['ESTADO']),operacion:get(o,['TIPO OPER.','TIPO']),rut:get(o,['RUT RECEPTOR']),receptor:get(o,['NOMBRE RECEPTOR']),neto:get(o,['NETO']),iva:get(o,['IVA']),total:get(o,['TOTAL']),ref:get(o,['FOLIO DOC. REF.','FOLIO DOC'])});
const nc=documents.filter(d=>/CREDITO|DEBITO|NOTA DE CREDITO|NOTA DE DEBITO/i.test(String(d.tipo||'')));const iv=documents.reduce((a,d)=>({neto:a.neto+n(d.neto),iva:a.iva+n(d.iva),total:a.total+n(d.total),docs:a.docs+1}),{neto:0,iva:0,total:0,docs:0});
post('Finalizando y preparando caché local',92);const snapshot={version:'8.0',fileName:e.data.fileName||'Maestro Excel',lastLoaded:Date.now(),sheets,metrics:{ine,sacos:{ventasSacos,kgSacos,items:sacItems},granel:{totalGranel,items:granelItems},iva:iv},documents,clients:[...clientsMap.values()].sort((a,b)=>a.nombre.localeCompare(b.nombre,'es')),guides,nc};self.postMessage({type:'result',snapshot});}catch(err){self.postMessage({type:'error',message:err?.message||String(err)})}};
