'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const os = require('node:os');
const path = require('node:path');
const fs = require('node:fs/promises');
const ExcelJS = require('exceljs');
const parser = require('../api/n8n-import-parser');
async function fixture(missing=false,formula=false){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'molino-test-'));const file=path.join(dir,'fixture.xlsx');const w=new ExcelJS.Workbook();const c=w.addWorksheet('CODIGOS');c.addRow(['CODIGO','PRODUCTO']);c.addRow(['X','Producto de prueba']);if(!missing){const d=w.addWorksheet('BASE DE DATOS');d.addRow(['FECHA','VALOR']);d.addRow(['2026-09-23',formula?{formula:'1+1'}:2]);}await w.xlsx.writeFile(file);return{file,dir};}
function capture(){const rows=[],findings=[],calls=[];const original=global.fetch;global.fetch=async(url,opts)=>{assert.ok(url.endsWith('/functions/v1/molino-n8n-trigger'));const b=JSON.parse(opts.body);calls.push(b);let data;if(b.action==='stage'){rows.push(...b.params.p_rows);data=b.params.p_rows.length;}else if(b.action==='findings'){findings.push(...b.params.p_errors);data=b.params.p_errors.length;}else if(b.action==='heartbeat'){data=true;}else throw Error('unexpected action');return new Response(JSON.stringify({ok:true,data}));};return{rows,findings,calls,restore:()=>global.fetch=original};}
test('valid XLSX is staged and explicitly not financially verified',async()=>{const x=await fixture();const c=capture();try{const r=await parser._internals.parseWorkbook({filePath:x.file,kind:'maestro',jobId:'test',workerId:'worker',token:'test'});assert.equal(r.status,'validado');assert.equal(r.rows_total,2);assert.equal(c.rows.length,2);assert.equal(r.summary.formulas_recalculated,false);assert.equal(r.summary.business_rules_verified,false);assert.equal(r.summary.publication_performed,false);}finally{c.restore();await fs.rm(x.dir,{recursive:true});}});
test('missing mandatory sheet blocks the job',async()=>{const x=await fixture(true);const c=capture();try{const r=await parser._internals.parseWorkbook({filePath:x.file,kind:'maestro',jobId:'test',workerId:'worker',token:'test'});assert.equal(r.status,'rechazado');assert.ok(c.findings.some(f=>f.error_code==='REQUIRED_SHEET_MISSING'));}finally{c.restore();await fs.rm(x.dir,{recursive:true});}});
test('formula without cached result is never accepted as valid source data',async()=>{const x=await fixture(false,true);const c=capture();try{const r=await parser._internals.parseWorkbook({filePath:x.file,kind:'maestro',jobId:'test',workerId:'worker',token:'test'});assert.equal(r.status,'rechazado');assert.equal(r.rows_error,1);}finally{c.restore();await fs.rm(x.dir,{recursive:true});}});
test('caller URLs cannot bypass signed storage allowlist',async()=>{await assert.rejects(parser._internals.downloadVerifiedFile('https://evil.test/file','a'.repeat(64),'/tmp/unused'),/not allowed/);await assert.rejects(parser._internals.downloadVerifiedFile('https://dadggurateghfumfcshz.supabase.co/other/storage/v1/object/sign/excel-imports/x','a'.repeat(64),'/tmp/unused'),/does not belong/);});

test('truncated XLSX is rejected before any staging call',async()=>{const x=await fixture();try{const b=await fs.readFile(x.file);await fs.writeFile(x.file,b.subarray(0,Math.floor(b.length/2)));await assert.rejects(parser._internals.validateArchive(x.file),/truncated_or_invalid/);}finally{await fs.rm(x.dir,{recursive:true});}});

test('cached formula zero survives ExcelJS getters and staging',async()=>{const x=await fixture();const w=new ExcelJS.Workbook();await w.xlsx.readFile(x.file);w.getWorksheet('BASE DE DATOS').getCell('B2').value={formula:'1-1',result:0};await w.xlsx.writeFile(x.file);const c=capture();try{const r=await parser._internals.parseWorkbook({filePath:x.file,kind:'maestro',jobId:'test',workerId:'worker',token:'test'});assert.equal(r.status,'validado');const row=c.rows.find(x=>x.sheet_name==='BASE DE DATOS');assert.equal(row.normalized_data.VALOR,0);assert.equal(row.source_data.B.result,0);}finally{c.restore();await fs.rm(x.dir,{recursive:true});}});
